language: cpp

notifications:
  slack: sriformalmethods:wSnZggI8D3mxI5uqDsElZbV2

dist: xenial  
sudo: true

compiler:
  # - clang (Disabling until boost and clang play well)
  - gcc
  
env:
  matrix:
    - CMAKE_BUILD_TYPE=Debug 
      ENABLE_COVERAGE=OFF
    - CMAKE_BUILD_TYPE=Release
      ENABLE_COVERAGE=OFF
    - CMAKE_BUILD_TYPE=Release
      ENABLE_COVERAGE=ON

addons:
  apt:
    update: true
    packages:
      - bison
      - flex
      - libgmp-dev
      - libboost-program-options-dev 
      - libboost-iostreams-dev
      - libboost-test-dev
      - libboost-thread-dev
      - libboost-system-dev
      - libreadline-dev
      - default-jre
      - gperf

install:
  - bash contrib/install_yices2.sh
  - bash contrib/install_opensmt2.sh
  - bash contrib/install_dreal4.sh
  - if [[ $ENABLE_COVERAGE == ON ]]; then 
      pip install --user cpp-coveralls;
    fi
  
script:
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DENABLE_COVERAGE=${ENABLE_COVERAGE} ..
  - make 
  - make check

after_script:
  - if [[ $ENABLE_COVERAGE == ON ]]; then
      coveralls -r .. -b . --gcov-options '\-lp';
    fi
  
notifications:
  slack: sallydevelopers:0ShJwlN0m6sOFGb5wfaJcLAB
